<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);CS8765;CS8767</NoWarn>
	</PropertyGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\AFMSDll\AFMSDll.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RnsLibrary">
      <HintPath>..\Dll\RnsLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Source\Form\MidSection\" />
    <Folder Include="Source\Form\SurfaceVelocity\" />
  </ItemGroup>

</Project>