<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="Krypton.Toolkit" Version="105.26.7.201" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AFMSDataReplicator\AFMSDataReplicator.csproj" />
    <ProjectReference Include="..\AFMSDischargeService\AFMSDischargeService.csproj" />
    <ProjectReference Include="..\AFMSDll\AFMSDll.csproj" />
    <ProjectReference Include="..\AFMSExtraLogger\AFMSExtraLogger.csproj" />
    <ProjectReference Include="..\AFMSExtraMonitor\AFMSExtraMonitor.csproj" />
    <ProjectReference Include="..\AFMSSettings\AFMSSettings.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RnsLibrary">
      <HintPath>..\Dll\RnsLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
